
package services;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServicesPharmacieService", targetNamespace = "http://services/", wsdlLocation = "http://med-sabir-pc:8080/pharmacieServer/ServicesPharmacieService?wsdl")
public class ServicesPharmacieService
    extends Service
{

    private final static URL SERVICESPHARMACIESERVICE_WSDL_LOCATION;
    private final static WebServiceException SERVICESPHARMACIESERVICE_EXCEPTION;
    private final static QName SERVICESPHARMACIESERVICE_QNAME = new QName("http://services/", "ServicesPharmacieService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://med-sabir-pc:8080/pharmacieServer/ServicesPharmacieService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICESPHARMACIESERVICE_WSDL_LOCATION = url;
        SERVICESPHARMACIESERVICE_EXCEPTION = e;
    }

    public ServicesPharmacieService() {
        super(__getWsdlLocation(), SERVICESPHARMACIESERVICE_QNAME);
    }

    public ServicesPharmacieService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICESPHARMACIESERVICE_QNAME, features);
    }

    public ServicesPharmacieService(URL wsdlLocation) {
        super(wsdlLocation, SERVICESPHARMACIESERVICE_QNAME);
    }

    public ServicesPharmacieService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICESPHARMACIESERVICE_QNAME, features);
    }

    public ServicesPharmacieService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServicesPharmacieService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IServicesPharmacie
     */
    @WebEndpoint(name = "ServicesPharmaciePort")
    public IServicesPharmacie getServicesPharmaciePort() {
        return super.getPort(new QName("http://services/", "ServicesPharmaciePort"), IServicesPharmacie.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IServicesPharmacie
     */
    @WebEndpoint(name = "ServicesPharmaciePort")
    public IServicesPharmacie getServicesPharmaciePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services/", "ServicesPharmaciePort"), IServicesPharmacie.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICESPHARMACIESERVICE_EXCEPTION!= null) {
            throw SERVICESPHARMACIESERVICE_EXCEPTION;
        }
        return SERVICESPHARMACIESERVICE_WSDL_LOCATION;
    }

}
